# general settings
name: train_ALKDN_x2_lkc9C64B8_L1_1000k
model_type: SRModel
scale: 2
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
#     (for lmdb)
#    dataroot_gt: /share/datasets/DF2K/DF2K_train_HR_sub.lmdb
#    dataroot_lq: /share/datasets/DF2K/LR_bicubic/DF2K_train_LR_bicubic_X2_sub.lmdb
#    filename_tmpl: '{}'
    dataroot_gt: /share/datasets/DF2K/HR
    dataroot_lq: /share/datasets/DF2K/LR_bicubic/x2
    filename_tmpl: '{}x2'
    io_backend:
       type: disk
#       (for lmdb)
#      type: lmdb

    gt_size: 96
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 12
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /root/tmp/experiments/datasets/Benchmark/Set5/HR
    dataroot_lq: /root/tmp/experiments/datasets/Benchmark/Set5/LR_bicubic/X2
    io_backend:
      type: disk

# network structures
network_g:
  type: ALKDN
  num_in_ch: 3
  num_feat: 64
  num_block: 8
  num_out_ch: 3
  upscale: 2
  conv: LargeKernelConv
  lk_size: 9

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: 

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [1000000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
    entity: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
